version: '2'
services:
    # web with xdebug - actency images
    webphp:
        # actency/docker-apache-php available tags: latest, 7.3., 7.2, 7.1-1.0, 7.1, 7.0, 5.6, 5.5, 5.4, 5.3
        image: actency/docker-apache-php:7.4
        ports:
            - "${WEB_PORT}:80"
            - "9000:9000"
        environment:
            - SERVERNAME=172.77.0.4
            - SERVERALIAS=example2.local *.example2.local
            - DRUSH_VERSION=8/9
            - DOCUMENTROOT=${DOCUMENT_ROOT}
            - APP_NAME=${APP_NAME}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DOCUMENT_ROOT=${DOCUMENT_ROOT}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - APP_ENV=${APP_ENV}
            - DEBUG=${DEBUG}
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
        volumes:
            - ./config/conf.d/://usr/local/etc/php/conf.d/
            - ./main/:/var/www/html/
            - /home/docker/.ssh/:/var/www/.ssh/
        command: echo 'cp ./config/host/host /etc/'
        depends_on:
            - database
        links:
            - database:mysql
        networks:
            - snare

    # database container - actency images
    database:
        # actency/docker-mysql available tags: latest, 5.7, 5.6, 5.5
        image: actency/docker-mysql:5.7
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        networks:
            - snare

    # phpmyadmin container - actency images
    phpmyadmin:
        image: actency/docker-phpmyadmin
        ports:
            - "${PHPADMIN_PORT}:80"
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - UPLOAD_SIZE=1G
        links:
            - database:mysql
        depends_on:
            - database
        networks:
            - snare

networks:
    snare:
        ipam:
            driver: default
            config:
                -   subnet: 172.77.0.0/16
                    gateway: 172.77.0.1