version: '2'
services:
    # web with xdebug - actency images
    webphp:
        build:
            context: ./docker
        ports:
            - "${WEB_PORT}:80"
            - "9000:9000"
        environment:
            - SERVERNAME=example.local
            - SERVERALIAS=example2.local *.example2.local
            - DRUSH_VERSION=8/9
            - DOCUMENTROOT=${DOCUMENT_ROOT}
            - APP_NAME=${APP_NAME}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DOCUMENT_ROOT=${DOCUMENT_ROOT}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - APP_ENV=${APP_ENV}
            - DEBUG=${DEBUG}
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
        volumes:
            - ./main/:/var/www/html/
            - ./docker/config/ini:/usr/local/etc/php
            - /home/docker/.ssh/:/var/www/.ssh/
        depends_on:
            - database
        links:
            - database:mysql

    # database container - actency images
    database:
        # actency/docker-mysql available tags: latest, 5.7, 5.6, 5.5
        image: actency/docker-mysql:5.7
        ports:
            - "${DATABASE_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}

    # phpmyadmin container - actency images
    phpmyadmin:
        image: actency/docker-phpmyadmin
        ports:
            - "${PHPADMIN_PORT}:80"
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - UPLOAD_SIZE=1G
        links:
            - database:mysql
        depends_on:
            - database
